services:
  datapowerDev:
    container_name: datapowerDev
    image: sankeerth520/datapower
    privileged: true
    environment:
      DATAPOWER_ACCEPT_LICENSE: 'true'
      DATAPOWER_INTERACTIVE: 'true'
      DATAPOWER_LOG_STDOUT: 'true'
      DATAPOWER_FAST_STARTUP: 'true'
      DATAPOWER_WORKER_THREADS: 4
      DP_WEB_MGMT: 'true'
    ports:
      - 9095:9095
      - 9001:9010
    volumes:
      - ./volumens/default/config:/drouter/config
      - ./volumens/default/local:/drouter/local     
      - ./volumens/apply/config:/opt/ibm/datapower/drouter/config
      - ./volumens/apply/local:/opt/ibm/datapower/drouter/local
    tty: true
    stdin_open: true   
version: '3'
 
